#!/bin/bash
#
# boxy - Script to run a custom, terminal-based IDE in a box powered by Docker
# Author: Jason Cox (dev@jasoncarloscox.com)

if [ -f .boxy/name ]; then
    tag="$(cat .boxy/name)"
fi

if [ "$1" = "--build" ]; then
    build=yes
    shift
fi

if [ "$1" = "--build-base" ]; then
    build_base="--build-base"
    shift
fi

if [ -n "$1" ]; then
    tag="$1"
fi

tag="${tag:-boxy-custom}"

# build image if needed
if [ -n "$build" ] || [ -z "$(sudo docker image ls -q $tag)" ]; then
    echo Building image
    /home/jason/code/boxy/custom/build $build_base $tag
fi

# allow docker to connect to X server for clipboard sharing
xhost local:root &> /dev/null || echo Clipboard sharing failed >2

user="$(id -un)"
full_dir="$(pwd)"
dir="${full_dir##*/}"

sudo docker run \
    --env DISPLAY \
    --hostname "$tag-$(hostname)" \
    --interactive \
    --tty \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
    --volume "$HOME/.ssh/id_rsa:/home/$user/.ssh/id_rsa" \
    --volume "$full_dir:/home/$user/$dir" \
    "$tag" \
    "$dir"
