#!/bin/bash
#
# boxy - Script to run a custom, terminal-based IDE in a box powered by Docker
# Author: Jason Cox (dev@jasoncarloscox.com)

if [ -f .boxy/name ]; then
    tag="$(cat .boxy/name)"
fi

if [ -n "$1" ]; then
    tag="$1"
fi

tag="${tag:-boxy-custom}"

# build image if needed
if [ -z "$(sudo docker image ls -q $tag)" ]; then
    echo Image not found -- building
    /home/jason/code/boxy/custom/build $tag
fi

# allow docker to connect to X server for clipboard sharing
xhost local:root &> /dev/null || echo Clipboard sharing failed >2

sudo docker run \
    --env DISPLAY \
    --hostname "$tag-$(hostname)" \
    --interactive \
    --tty \
    --volume /tmp/.X11-unix:/tmp/.X11-unix \
    $tag \
    /bin/bash
