#!/bin/bash
#
# boxy-install - cleanly install system packages inside the container

# give sudo the password - PASSWORD will be replaced in container
echo PASSWORD | sudo -S echo

# install desired packages
sudo apt-get update
sudo apt-get install -y "$@"
sudo rm -rf /var/lib/apt/lists/*
